"""TOML input file reader for GyroJAX.

Load a simulation config from a .toml file:

    from gyrojax.io.input_file import load_config, save_config_template
    cfg = load_config("myrun.toml")

TOML format example (gyrojax/examples/template.toml):

    [simulation]
    Npsi = 16
    Ntheta = 32
    Nalpha = 32
    N_particles = 50000
    n_steps = 500
    dt = 0.05
    fused_rk4 = true
    output_file = "run.h5"
    checkpoint_interval = 50

    [physics]
    R0 = 1.0
    a = 0.18
    B0 = 1.0
    q0 = 1.4
    q1 = 0.5
    Ti = 1.0
    Te = 1.0
    R0_over_LT = 6.9
    R0_over_Ln = 2.2
    R0_over_LTe = 6.9
    beta = 0.0

    [dtype]
    position = "float32"
    velocity = "float32"
    weight = "float32"
    mu = "float32"
    phi = "float32"
    A_par = "float32"
    delta_n = "float32"
    geom = "float32"

    [flags]
    use_cn_weights = false
    absorbing_wall = false
    zonal_preserving_spread = true
    use_radial_gaa = true
    single_mode = false
"""

import tomllib  # Python 3.11+ stdlib
from pathlib import Path
from typing import Union
from gyrojax.simulation_fa import SimConfigFA, DtypeConfig


def load_config(path: Union[str, Path]) -> SimConfigFA:
    """Load SimConfigFA from a TOML file.

    Sections:
      [simulation] → top-level SimConfigFA fields (grid, particles, steps)
      [physics]    → physics parameters (R0, LT, beta, etc.)
      [dtype]      → DtypeConfig fields
      [flags]      → boolean feature flags

    All sections are optional; missing keys use SimConfigFA defaults.
    """
    with open(path, "rb") as f:
        data = tomllib.load(f)

    # Flatten all sections except [dtype] into kwargs
    kwargs = {}
    for section in ("simulation", "physics", "flags"):
        kwargs.update(data.get(section, {}))

    # Handle [dtype] section separately
    dtype_data = data.get("dtype", {})
    if dtype_data:
        kwargs["dtype_config"] = DtypeConfig(**dtype_data)

    return SimConfigFA(**kwargs)


def save_config_template(path: Union[str, Path], cfg: SimConfigFA = None):
    """Write a TOML template file. If cfg provided, uses its values; otherwise uses defaults."""
    if cfg is None:
        cfg = SimConfigFA()

    dc = cfg.dtype_config

    template = f"""# GyroJAX Simulation Input File
# Generated by gyrojax.io.input_file.save_config_template()
# Run with: python -m gyrojax run {path}

[simulation]
Npsi = {cfg.Npsi}
Ntheta = {cfg.Ntheta}
Nalpha = {cfg.Nalpha}
N_particles = {cfg.N_particles}
n_steps = {cfg.n_steps}
dt = {cfg.dt}
fused_rk4 = {"true" if cfg.fused_rk4 else "false"}
output_file = "{cfg.output_file}"
checkpoint_interval = {cfg.checkpoint_interval}

[physics]
R0 = {cfg.R0}
a = {cfg.a}
B0 = {cfg.B0}
q0 = {cfg.q0}
q1 = {cfg.q1}
Ti = {cfg.Ti}
Te = {cfg.Te}
R0_over_LT = {cfg.R0_over_LT}
R0_over_Ln = {cfg.R0_over_Ln}
R0_over_LTe = {cfg.R0_over_LTe}
beta = {cfg.beta}
pert_amp = {cfg.pert_amp}

[dtype]
# Safe to lower: velocity, mu, phi, A_par  (bfloat16 or float16)
# Unsafe to lower: position, weight, delta_n, geom  (keep float32)
position = "{dc.position}"
velocity = "{dc.velocity}"
weight = "{dc.weight}"
mu = "{dc.mu}"
phi = "{dc.phi}"
A_par = "{dc.A_par}"
delta_n = "{dc.delta_n}"
geom = "{dc.geom}"

[flags]
use_cn_weights = {"true" if cfg.use_cn_weights else "false"}
absorbing_wall = {"true" if cfg.absorbing_wall else "false"}
zonal_preserving_spread = {"true" if cfg.zonal_preserving_spread else "false"}
use_radial_gaa = {"true" if cfg.use_radial_gaa else "false"}
single_mode = {"true" if cfg.single_mode else "false"}
"""
    with open(path, "w") as f:
        f.write(template)
    print(f"Wrote config template to {path}")
